# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: journal_app_development

# test:
#   <<: *default
#   database: journal_app_test

# production:
#   <<: *default
#   database: journal_app_production
#   username: journal_app
#   password: <%= ENV['JOURNAL_APP_DATABASE_PASSWORD'] %>

default: &default
  adapter: 'postgresql'
  host: containers-us-west-59.railway.app
  username: postgres
  password: 3RN9vhIV0pROZ0RIu0S0
  port: 7382

development:
  <<: *default
  database: railway

test:
  <<: *default
  database: journal_app_test

production:
  <<: *default
  database: railway
